### ISSUE TITLE
Provide more helpful error information for trace below

### ISSUE THREAD

**Issue by mwhipple** [mwhipple/logman-api#3]
```
12:40:24.993 [ajp-bio-8009-exec-4] ERROR o.h.c.c.l.LoggingManagingController - Could not update log level
java.lang.IllegalStateException: Invalid initialization state
	at com.mattwhipple.logman.LogManFactory.getLogMan(LogManFactory.java:74) ~[logman-api-0.0.1.jar:na]
	at org.....LoggingManagingController.getLogMan(LoggingManagingController.java:25) ~[...]
	at org....LoggingManagingController.setRootLevel(LoggingManagingController.java:36) ~[...]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
```

Seems to be environmental

**Comment by mwhipple** [comment]
The ultimate cause of this issue was that the logback binding package had been compiled with Java 8 which was understandably causing issued in a Java 7 environment. As the initialization logic is being gutted this is no longer relevant.
